version: '3'
services:
  data-collector-service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}

networks:
  default:
    name: my-network
    external: true